apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  replicas: 1  # Number of pod replicas (you can adjust this based on your needs)
  selector:
    matchLabels:
      app: wisecow  # This label is used to identify the pods for this deployment
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow
          image: mani6288/wisecow-app:latest  # Replace with your image name
          ports:
            - containerPort: 4499
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/tls
              readOnly: true
          command: ["/bin/bash", "-c"]
          args:
            - >
              openssl s_server -accept 4499
              -cert /etc/tls/tls.crt
              -key /etc/tls/tls.key
              -www
      volumes:
        - name: tls-certs
          secret:
            secretName: wisecow-tls
