apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  replicas: 1  # Number of pod replicas (you can adjust this based on your needs)
  selector:
    matchLabels:
      app: wisecow  # This label is used to identify the pods for this deployment
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow
          image: mani6288/wisecow-app:latest  # Replace with your image name
          ports:
            - containerPort: 4499
