apiVersion: v1
kind: Service
metadata:
  labels:
    app: wisecow
  name: wisecow-deployment
spec:
  ports:
  - port: 4499
    protocol: TCP
    targetPort: 4499
    nodePort: 32100
  selector:
    app: wisecow
  type: NodePort
