apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow  # This should match the label in the deployment
  ports:
    - protocol: TCP
      port: 4499  # External port the service will expose
      targetPort: 4499  # The container's internal port (where the app listens)
