name: End to End CI/CD workflow for wisecow application by Accuknox Assessment

on:
  push:
    branches:
      - main

jobs:
  
  Build_Docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.REGISTRY_USERNAME }}/wisecow-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.REGISTRY_USERNAME }}/wisecow-app:latest

      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0
        with:
          cluster_name: wisecow-cluster

      - name: Wait for Cluster to be ready & Check cluster info
        run: |
          kubectl wait --for=condition=Ready nodes --all --timeout=60s
          kubectl config current-context
          kubectl get nodes

      - name: Verify kubectl
        run: kubectl version --client

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml

      - name: List all services for debugging
        run: kubectl get svc

      - name: List all Pods for debugging
        run: |
          kubectl get pods
          wait: 120s
