name: End to End CI/CD workflow for wisecow application by Accuknox Assessment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/wisecow-app .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest
  Kind:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'
          
      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0
        with:
          cluster_name: wisecow-cluster

      - name: Wait for cluster to be ready
        run: |
          kubectl wait --for=condition=Ready nodes --all --timeout=60s
          
      - name: Check cluster info
        run: |
          kubectl config current-context
          kubectl get nodes

      # Set up kubeconfig from GitHub Secrets
      - name: Set kubeconfig
        run: |
            mkdir -p $HOME/.kube
            cat ~/.kube/config | base64 -d > $HOME/.kube/config

     # Verify kubectl is working
      - name: Verify kubectl
        run: kubectl version --client

      - name: Apply Kubernetes Deployment
        run: |
            kubectl apply --dry-run=client -f deployment.yml
            kubectl apply --dry-run=client -f service.yml
        working-directory: ./  # Ensure you're running this from the root or correct directory

      - name: List all services for debugging
        run: kubectl get svc

      - name: List all Pods for debugging
        run: kubectl get pods
