name: End to End CI/CD workflow for wisecow application by Accuknox Assessment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Get Nodes
        run: kubectl get nodes

      - name: Apply Kubernetes Deployment and Service
        run: |
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml

      - name: List all services
        run: |
          kubectl wait --for=condition=available --timeout=300s deployment/wisecow-deployment
          kubectl get deploy
          kubectl describe deploy wisecow-deployment
          kubectl wait --for=condition=ready pod -l app=wisecow --timeout=300s
          kubectl get pod -o wide
          kubectl get svc
