name: End to End CI/CD workflow for wisecow application by Accuknox Assessment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/wisecow-app .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          kubectl-version: 'latest'

      # Set up kubeconfig from GitHub Secrets
      - name: Set kubeconfig
        run: |
            mkdir -p $HOME/.kube
            echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config

     # Verify kubectl is working
      - name: Verify kubectl
        run: kubectl version --client

      - name: Apply Kubernetes Deployment
        run: |
            kubectl apply -f deployment.yml
            kubectl apply -f service.yml
        working-directory: ./  # Ensure you're running this from the root or correct directory

      - name: List all services for debugging
        run: kubectl get svc

      - name: List all Pods for debugging
        run: kubectl get pods
