name: End to End CI/CD workflow for wisecow application by Accuknox Assessment

on:
  push:
    branches:
      - main

jobs:
  Pre-Requi:
    runs-on: ubuntu-latest
    steps:            
      - name: List files
        run: |
          cd ../../
          if [ -f "deployment.yml" ]; then
            echo "deployment.yml exists."
            exit 0
          else
            echo "deployment.yml does not exist."
            exit 1
          fi
          
  Build_Docker_image:
    runs-on: ubuntu-latest
    needs: Pre-Requi
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest

  kind_Cluster:
    runs-on: ubuntu-latest
    needs: Build_Docker_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0
        with:
          cluster_name: wisecow-cluster

      - name: Wait for Cluster to be ready & Check cluster info
        run: |
          kubectl wait --for=condition=Ready nodes --all --timeout=60s
          kubectl config current-context
          kubectl get nodes

      - name: Set kubeconfig
        run: |
          mkdir -p $HOME/.kube
            echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Verify kubectl
        run: kubectl version --client
        
  Deploy_to_Kind:
    runs-on: ubuntu-latest
    needs: kind_Cluster
    steps:
      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f ../../deployment.yml
          kubectl apply -f ../../service.yml
        working-directory: ./  # Ensure you're running this from the correct directory

      - name: List all services for debugging
        run: kubectl get svc

      - name: List all Pods for debugging
        run: kubectl get pods
